### ISSUE TITLE
The admin should be able to create a new user.

### ISSUE THREAD

**Issue by adityabisht02** [adityabisht02/BetterPoll-Backend#14]
Find the admin/users.js file and create an api to add new users.

**Comment by ddanielsantos** [comment]
its still available?

**Comment by leksyking** [comment]
I want to do this

**Comment by adityabisht02** [comment]
I am assigning both of you, go ahead!

**Comment by adityabisht02** [comment]
If u would like to work on a similar issue check issue #3  and #4

**Comment by leksyking** [comment]
Ok, cook
