### ISSUE TITLE
What to use for email verification?

### ISSUE THREAD

**Issue by adityabisht02** [adityabisht02/BetterPoll-Backend#20]
Should we go with something like sendGrid or just use nodemailer.

**Comment by Teixi-dev** [comment]
Nodemailer is a great option. I recommend you use Interface for abstract logic and implements any one in other moment.

**Comment by adityabisht02** [comment]
But nodemailer requires a google account with particular settings , ig the person using this source code can take care of that account.

**Comment by leksyking** [comment]
Okay for nodemailer
You can generate app password from your mail which will enable you to send mails from that email

**Comment by leksyking** [comment]
Sendgrid provides dynamic templates by the way. Or is there a way one can include a good template with nodemailer?

**Comment by adityabisht02** [comment]
What kind of templates are u referring to

**Comment by adityabisht02** [comment]
What exactly do u mean by a template here

**Comment by leksyking** [comment]
something like how the body of the mail looks like, like the designs and all

**Comment by adityabisht02** [comment]
We can use html for nodemailer right? Like this: 
![image](https://user-images.githubusercontent.com/89146189/195522080-cc648c47-7106-4f2c-bf48-259a2dafccd7.png)

**Comment by leksyking** [comment]
Yes
