### ISSUE TITLE
Contributors kindly test your api before making a PR, if u can attach an ss with the PR that would be even better

### ISSUE THREAD

**Issue by adityabisht02** [adityabisht02/BetterPoll-Backend#22]

**Comment by AmanPachori** [comment]
Hey @adityabisht02  can I make PR template which will ask contributors about it ?

**Comment by AmanPachori** [comment]
Hey @adityabisht02  should I create a new Issue for that ?

**Comment by adityabisht02** [comment]
Yeah sure ,dont put too many requirements though .
