### ISSUE TITLE
The admin should be able to edit-menu

### ISSUE THREAD

**Issue by adityabisht02** [adityabisht02/BetterPoll-Backend#23]
U can create an api for edit-menu under admin/messmanagement.js , take the day and the meal type (breakfast, lunch or dinner) from the request body.

**Comment by PeanutPancakes** [comment]
Hey @adityabisht02, I'd like to implement this one. Will you assign it to me please?

**Comment by adityabisht02** [comment]
Yes go ahead!

**Comment by AmanPachori** [comment]
Hey @Jothebanner are you still working on it?

**Comment by PeanutPancakes** [comment]
Hey @AmanPachori. Yes, I'll submit it soon.

**Comment by PeanutPancakes** [comment]
Hey @adityabisht02, the date is currently set as a VARCHAR(25), should I change that to a DATE type (YYYY-MM-DD) or is there a format you had in mind that uses the VARCHAR?

**Comment by adityabisht02** [comment]
See ill tell you the flow, the menu for 7 days of the week will be in the DB. We have to make sure the app updates the menu daily. 
Do we even need date or can we just use day as a parameter. What do u suggest?

**Comment by PeanutPancakes** [comment]
After a bit of research, I think we should just use Unix time as the primary key. Unix time is simple and robust; reading it right out of the database would be rough, but we can just convert it to a date when retrieving the record. 

If I trim the hours, minutes and seconds then we should be able to receive most date formats, making the front-end implementation simple.

**Comment by adityabisht02** [comment]
Hey @Jothebanner I looked at your PR it looks good however we do not need to keep a date with the menu cause we need to set it for seven days of the week and it does not change every week. So only keeping day instead of date should suffice.

**Comment by adityabisht02** [comment]
And UNIX timestamp seems like a good way to keep track of dates, we can use this while marking users' mess attendance.

**Comment by PeanutPancakes** [comment]
Ok, so I should just use something like 1-7 for the primary keys?

**Comment by adityabisht02** [comment]
Yeah
