### ISSUE TITLE
Add an api for admin to edit user info

### ISSUE THREAD

**Issue by adityabisht02** [adityabisht02/BetterPoll-Backend#24]
Create this under admin/users.js. You can refer to other apis in the file. Take the new user details from request body.

**Comment by Harsh-garg-coder** [comment]
can you assign this issue to me?

**Comment by adityabisht02** [comment]
Sure!

**Comment by Harsh-garg-coder** [comment]
@adityabisht02 what to do if the user does not exists?(create a user or send a response saying bad request)

**Comment by adityabisht02** [comment]
bad request

**Comment by Harsh-garg-coder** [comment]
ok @adityabisht02

**Comment by Harsh-garg-coder** [comment]
@adityabisht02 is there any particular reason of phone to be a int instead of varchar?

**Comment by adityabisht02** [comment]
No it should be a varchar, I accidentaly made it int
