### ISSUE TITLE
Create the user signUp api 

### ISSUE THREAD

**Issue by adityabisht02** [adityabisht02/BetterPoll-Backend#3]
You can find the login.js file under apis and work on the signup api. Write the sql query and import the sqlpool to write the query.

You can refer to the initialiseDB function for reference on how to create queries using mysql.pool.

**Comment by raji2004** [comment]
pls assign me this issue

**Comment by IRSHIT033** [comment]
I had previous experience on this can u assign me

**Comment by adityabisht02** [comment]
@IRSHIT033 u can work on this @raji2004 i have assigned u another issue

**Comment by raji2004** [comment]
how do i create an sql database sorry im used to mongodb

**Comment by adityabisht02** [comment]
u can install xampp and create a db on phpmyadmin, if ure not comfortable I can assign someone else so do let me know.

**Comment by raji2004** [comment]
> u can install xampp and create a db on phpmyadmin, if ure not comfortable I can assign someone else so do let me know.
yes please assign it to somepne else

**Comment by leksyking** [comment]
Is password not needed?

**Comment by adityabisht02** [comment]
I was thinking since this is an application where user is created by admin, we can simply have email verification instead of a password. What do you think should we have a password?

**Comment by leksyking** [comment]
If the user is created by the admin, then only login functionality should be available for the users because creation of users by the admin is same as sign up right?
Unless the sign up functionality will only be for admins

**Comment by adityabisht02** [comment]
yeah makes sense ill remove the sign up issue. There will only be a login based on whether the user exists in the users table.
