### ISSUE TITLE
Create the user login api

### ISSUE THREAD

**Issue by adityabisht02** [adityabisht02/BetterPoll-Backend#4]
refer to issue #3

**Comment by raji2004** [comment]
pls assign me this issue

**Comment by adityabisht02** [comment]
go ahead!

**Comment by adityabisht02** [comment]
@leksyking I have closed the signup issue now the user will login based on whether admin has created them in the users table

**Comment by leksyking** [comment]
Alright, I would like to jump on this.
Basic login functionality right?
- user enters email
- check whether email is present in the database
- the return success
Any other thing?

**Comment by adityabisht02** [comment]
Nope sounds good
