### ISSUE TITLE
Create an admin sign up api

### ISSUE THREAD

**Issue by adityabisht02** [adityabisht02/BetterPoll-Backend#43]
Find the admin/login.js file. Take the sign up information from request body and use it to create an admin.
You can look at the admin table for the fields you need to sign up an admin.

**Comment by cate865** [comment]
Hi, I'd like work on these two issues. Could you assign them to me?

**Comment by Kishore-abhimanyu** [comment]
Can you assign me this issue?

**Comment by adityabisht02** [comment]
@cate865 U can work on this

**Comment by harpreet0102** [comment]
Hey @adityabisht02 !
I would like to work on these two issues. Could you assign this to me.

Thanks!

**Comment by adityabisht02** [comment]
Sure go ahead!

**Comment by adityabisht02** [comment]
@cate865 please let @harpreet0102 know if you are still working on it else she can go ahead.
