### ISSUE TITLE
Create admin sign in 

### ISSUE THREAD

**Issue by adityabisht02** [adityabisht02/BetterPoll-Backend#44]
If the admin username and password are present in the table ,send a positive response. 
U can take the username and password from request body. Use only the username and password to log in , other fields
like email and id are not required here.

**Comment by jjv1602** [comment]
@adityabisht02 just to confirm do you want a frontend for login page ?
If yes then if possible you can assign me

**Comment by adityabisht02** [comment]
This is only for the backend

**Comment by nalowageena** [comment]
Can you please assign me this task?

**Comment by adityabisht02** [comment]
sure go ahead!

**Comment by nalowageena** [comment]
Hey @adityabisht02. I get an error when I try to run `npm run initialise-db`.
I checked the `initialise.db` file and there are some extra lines that don't seem to find their place. They might have been added while resolving merge conflicts.
 
Do you mind looking into that?
![image](https://user-images.githubusercontent.com/77391048/197152654-e2217613-a6be-4031-96da-09920929ec75.png)

**Comment by adityabisht02** [comment]
I fixed these yesterday take a pull once.

**Comment by nalowageena** [comment]
Okay thanks, I'll go ahead then

**Comment by harpreet0102** [comment]
Hi @adityabisht02 Could you assign this to me.

Thanks

**Comment by adityabisht02** [comment]
sure @harpreet0102 go ahead !
