### ISSUE TITLE
Hash passwords for the admin passwords

### ISSUE THREAD

**Issue by adityabisht02** [adityabisht02/BetterPoll-Backend#46]
1. We are storing admin passwords in the database.
2. Hash the password before storing it in the table, you can use bcrypt library for this.

**Comment by adityabisht02** [comment]
This issue needs to be done after #43 is complete.

**Comment by surreal30** [comment]
Hi
Assign this to me please.

Edit: Do I need to hash the passwords in js only?

**Comment by adityabisht02** [comment]
Yeah check out the bcrypt npm package , I recommend u use that

**Comment by adityabisht02** [comment]
Isuue #43 is not complete yet though

**Comment by Hares27** [comment]
Can you assign this issue to me. I know how to use bcrypt.

**Comment by adityabisht02** [comment]
@Hares27 U can work on this.

**Comment by harpreet0102** [comment]
Hi @adityabisht02 
Could you assign this to me.

Thanks.

**Comment by adityabisht02** [comment]
@harpreet0102 sure use bcrypt for the sign up and sign in apis and test them as well.
