### ISSUE TITLE
Deployment suggestions

### ISSUE THREAD

**Issue by adityabisht02** [adityabisht02/BetterPoll-Backend#48]
Heroku is removing its free tier soon, where can I deploy this server for testing?

**Comment by sanket95droid** [comment]
It's sad for developers that Heroku is ending its free service
I've heard that render is a good alternative to Heroku
https://render.com/free#:~:text=Build%2C%20deploy%2C%20and%20run%20your,Render%2C%20no%20credit%20card%20needed.

**Comment by adityabisht02** [comment]
For server ? I have heard of render ill check it out
