### ISSUE TITLE
Create a function to generate a random number of 5 digits

### ISSUE THREAD

**Issue by adityabisht02** [adityabisht02/BetterPoll-Backend#5]
Create this under messmanagement.js

**Comment by Paras-code-007** [comment]
@adityabisht02  can you assign this issue to me??

**Comment by adityabisht02** [comment]
Sure go ahead!

**Comment by vaibhavg20comp** [comment]
Hey Can I work on this issue please  ?

**Comment by adityabisht02** [comment]
hey this issue already has a pull request , u can try other issues which havent been done
