### ISSUE TITLE
Create a messattendance table

### ISSUE THREAD

**Issue by adityabisht02** [adityabisht02/BetterPoll-Backend#51]
1. Refer to the messcodes table inside inititaliseDB.js, and create a messattendance table.
2. The table should have the users' name, breakfast , lunch and dinner attendance as columns.
3. The attendance will be marked as P for present and A for absent.

**Comment by chinmaym07** [comment]
Hey @adityabisht02 Can I work on this ?

**Comment by adityabisht02** [comment]
go ahead
