### ISSUE TITLE
How to manage shuttle booking 

### ISSUE THREAD

**Issue by adityabisht02** [adityabisht02/BetterPoll-Backend#64]
1. There are multiple shuttles which will be running from campus and I need to manage booking for each of them.
2. Do I make separate tables for every shuttle and mark attendance there or is there a better way of managing this.

**Comment by udaya19** [comment]
You can make single table named "Shuttle Services" and you can add all the information like service name, source, destination  and number of seats. 
You can make another table for booking and use foreign key to connect to tables "shuttle service" and "users"

**Comment by adityabisht02** [comment]
Sorry for replying so late. I am planning on resuming work on this soon.
