### ISSUE TITLE
Create a table which contains breakfast, lunch and dinner for 7 days of the week

### ISSUE THREAD

**Issue by adityabisht02** [adityabisht02/BetterPoll-Backend#8]
You can create an add-menu api under admin/messmanagement.js , refer to user/login.js for how to create apis.

**Comment by mukunddeepak** [comment]
Can i work on this please?

**Comment by adityabisht02** [comment]
Yeah go ahead!

**Comment by mukunddeepak** [comment]
Can you please give me a bit more details on what exactly you would like the add-menu api to do?

**Comment by adityabisht02** [comment]
My bad, this issue is only for creating the table for breakfast ,lunch ,dinner for seven days of the week. You can create the query for this table in the initialiseDB.js file.

**Comment by adityabisht02** [comment]
The add-menu api will be created after this table is created.
